definitions:
  common.APIResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
      total_data:
        type: integer
    type: object
  orders.OrderDetail:
    properties:
      item:
        type: string
      order_id:
        description: gorm.Model
        type: integer
      qty:
        type: integer
    type: object
  orders.OrderRequest:
    properties:
      customer:
        type: string
      description:
        type: string
      employee_id:
        type: integer
      location:
        type: string
      order_details:
        items:
          $ref: '#/definitions/orders.OrderDetail'
        type: array
      status:
        type: string
    type: object
  users.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  users.LoginResponse:
    properties:
      token:
        type: string
    type: object
  users.SignUpRequest:
    properties:
      password:
        type: string
      re_type_password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
host: https://gotrack-production.up.railway.app/swagger/index.html
info:
  contact: {}
  description: This is documentation GoTrack.
  title: GoTrack Documentation
  version: 1.0.0
paths:
  /api/order:
    post:
      consumes:
      - application/json
      description: Creates a new order with details provided in the request body.
      parameters:
      - description: Order data
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/orders.OrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created the order
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/orders.OrderRequest'
              type: object
        "400":
          description: Bad request, invalid data provided
          schema:
            $ref: '#/definitions/common.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.APIResponse'
      summary: Create a new order
      tags:
      - Orders
  /api/order/{id}:
    delete:
      consumes:
      - application/json
      description: Remove a order from the database by its ID
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/common.APIResponse'
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/common.APIResponse'
        "404":
          description: Order not found
          schema:
            $ref: '#/definitions/common.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.APIResponse'
      security:
      - Bearer: []
      summary: Delete a order by ID
      tags:
      - Order
    put:
      consumes:
      - application/json
      description: Updates a new order with details provided in the request body.
      parameters:
      - description: Order data
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/orders.OrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated the order
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/orders.OrderRequest'
              type: object
        "400":
          description: Bad request, invalid data provided
          schema:
            $ref: '#/definitions/common.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.APIResponse'
      summary: Update a new order
      tags:
      - Orders
  /api/order/delivery/{id}:
    post:
      consumes:
      - application/json
      description: Deliverys a new order with details provided in the request body.
      parameters:
      - description: ID Order
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated the order
          schema:
            $ref: '#/definitions/common.APIResponse'
        "400":
          description: Bad request, invalid data provided
          schema:
            $ref: '#/definitions/common.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.APIResponse'
      summary: Delivery order
      tags:
      - Delivery Orders
  /api/order/success/{id}:
    post:
      consumes:
      - multipart/form-data
      description: Delivery Success
      parameters:
      - description: Bukti Pengiriman Success
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated the order
          schema:
            $ref: '#/definitions/common.APIResponse'
        "400":
          description: Bad request, invalid data provided
          schema:
            $ref: '#/definitions/common.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.APIResponse'
      summary: Delivery Success
      tags:
      - Delivery Success
  /api/orders:
    get:
      consumes:
      - application/json
      description: Get all orders with search and pagination
      parameters:
      - description: Search term
        in: query
        name: search
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved orders
          schema:
            $ref: '#/definitions/common.APIResponse'
        "400":
          description: Bad request, invalid data provided
          schema:
            $ref: '#/definitions/common.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/common.APIResponse'
      summary: Get all orders
      tags:
      - Orders
  /api/users/login:
    post:
      consumes:
      - application/json
      description: This endpoint is used for user login
      parameters:
      - description: Login Request
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/users.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/common.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/users.LoginResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.APIResponse'
      summary: User Login
      tags:
      - Users
  /api/users/signup:
    post:
      consumes:
      - application/json
      description: This endpoint is used for user signup
      parameters:
      - description: Sign Up Request
        in: body
        name: signUpRequest
        required: true
        schema:
          $ref: '#/definitions/users.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/common.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.APIResponse'
      summary: User Signup
      tags:
      - Users
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
